### ISSUE TITLE
Trimming Badge Selection

### ISSUE THREAD

**Issue by alichtman** [jaywcjlove/awesome-mac#389]
Leading off of #386, we're going to do a review of the badges supported in the repo.

```
1. Open-Source Software
2. Freeware 
3. hot 
4. Recommend 
5. Must Have 
6. App Store 
7. Star Rating
```

I propose we trim this to:

```
1. Open-Source
2. Freeware 
3. App Store
```

to kill some of the redundancy and clean it all up a bit.

**Comment by jaywcjlove** [comment]
@alichtman good!

**Comment by heldev** [comment]
About "Recommended":
There are awesome lists that don't have this badge because they are awesome lists and don't have "not recommeded" apps. All apps in the lists are unique or already too good to be judged. If some app is better by all means than another app in the list then the second app just should not be on the list. If there are no alternatives to the app it's automatically the recommended app of its kind. Plus this approach will allow avoiding holy wars like Sublime Text vs Atom, Postman vs Insomnia, Safari vs Chrome ... Some of them are especially tough if we consider the diverse audience of the list (even if we simplify the situation and imagine that there only two "types" of readers Designers and Devs ).
 
And another issue who (and how) is going to determine if an app is "Recommended" (again taking into account that the list is a collaborative project) ?

**Comment by alichtman** [comment]
You're right, in my opinion.
